services:
  raphtory_graphql_server:
    build:
      context: ./graphql_server
      dockerfile: Dockerfile
    image:
      raphtory_graphql_server
    container_name: raphtory_graphql_server
    ports:
      - "1736:1736"
    volumes:
      - ./graphql_server/graphs:/usr/src/graphql_server/graphs
    networks:
      - main_net

  neo4j:
    image: neo4j:2025.04.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data_volume:/data
      - neo4j_logs_volume:/logs
    networks:
      - main_net
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescaledb_volume:/home/postgres/pgdata/data
    networks:
      - main_net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgresql_admin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - postgres_admin_volume:/var/lib/pgadmin
    networks:
      - main_net
    restart: unless-stopped

volumes:
  timescaledb_volume:
  postgres_admin_volume:
  neo4j_data_volume:
  neo4j_logs_volume:

networks:
  main_net:
    driver: bridge
